### ISSUE TITLE
[FEATURE] DustKey Integrated Deposit

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#100]
**Аbstract**
Key Halves for Coin/Token Gateways in Wallet

Tunnel Key:
Using fraction field make min 5 places, then randomize those automatically for user.
Gateway sees:

56.0087394

87394 is the key

Key + Tunnel (one time use)

Gateway node receives XXX deposit, checks appended ending key against tunnel DB

**Motivation and Purposes**
Traditional tunnels just do not fit deposit elegantly for users, process needs to be more automated to be in the wallet.

**Specification**

User goes to receive, they press: Receive DustKey""

API to gateway as: dustKey.deposit""

The gateway returns them the DustKey, for their address/deposit

This sum would be user inputted amount, plus, the DustKey.

I want to deposit 50Coins

Gateway says: Your DustKey is: 0.0067362
you must send 50.0067362

**Backwards Compatibility**
Can your proposition affect any existing features?

If user wants a manual tunnel they just use the gateway pages outside client.

**Comment by iammortimer** [comment]
test implementation running on SENT gw:
https://sentgw.mortysnode.nl/dustkey/
and paste your TN address behind it.

Returns a 6 digit number that must be used in the amount as the last digits (also returns the number for already created tunnels).
When deposit to the GW address is detected and the last 6 digits match an address in the DB on the gateway the funds will be transferred to that address.

**Comment by greywolf42069** [comment]
https://arrrgw.mortysnode.nl/dustkey/address

Queries Key to user

This is just piratechain ARRR gw

**Comment by BlackTurtle123** [comment]
Closed for now
