### ISSUE TITLE
[FEATURE] QR Code enablement for Receiving TN or Waves

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#103]
**Аbstract**
Allow QR Code to be generated, which can be Parsed by the native Waves and TN wallet clients to allow field autofill

**Motivation and Purposes**
This is to make the rate of failed gateway deposits decrease from 20%

**Comment by BlackTurtle123** [comment]
Won't be done since dev capacity is down and this has no priority, also we couldn't find how to add attachments to waves qr
