### ISSUE TITLE
[BUG] Cannot Search by Ticker on Dex

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#118]
**Describe the bug**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/55455281/77670565-61fb0c00-6f54-11ea-9574-59ec13ca87b9.png">

**To Reproduce**
1. Go to Exchange
2. Click on Search Box
3. Type ARRR

**Expected behavior**
It should produce the listing for Pirate Chain

**Comment by BlackTurtle123** [comment]
What we expect to work:
- Any ticker (qualified and status 2) should be founded under any circumstances, partly or exact matches
So AC should show ACL for example. 
- Any asset should be able to be traded against any qualified or gateway asset
- qualified should be able to trade against qualified


Assets needs to be found by 
-assetid
-ticker
-asset name
-or a part from any off the above

------order structure------
Qualified and gateway assets should be shown as first. 
Volume is the second search criteria

**Comment by greywolf42069** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/55455281/77771759-1e1c0b80-7015-11ea-8651-2dfb59792fa2.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/55455281/77771795-2a07cd80-7015-11ea-8629-985f9f16762e.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/55455281/77771819-3429cc00-7015-11ea-8625-5162ca4c5067.png">

**Comment by greywolf42069** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/55455281/77772015-77843a80-7015-11ea-8f8c-0a74630e1ff6.png">
 
"TN / (assetID)"

**Comment by BlackTurtle123** [comment]
Unverified assets are left out right now.

**Comment by BlackTurtle123** [comment]
https://privatenode.blackturtle.eu/addresses/data/3JwdMmF7xEack9y8SJ4VeQ4UX2qmu1jCoWa?matches=^ticker_<.*$  
<= get tickers from oracle

https://privatenode.blackturtle.eu/addresses/data/3JwdMmF7xEack9y8SJ4VeQ4UX2qmu1jCoWa?matches=^status_<.*$  
<= get status from oracle

**Comment by xucito** [comment]
The assets need to be assigned ticker values in the data-service

**Comment by BlackTurtle123** [comment]
I made a tool which auto updates every 5 min from the oracle.
