### ISSUE TITLE
[BUG]  Cant Search by AssetID in dex

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS]
 - Browser/JVM [e.g. chrome, safari]

**Additional context**

**Comment by BlackTurtle123** [comment]
Still not working for me. Does it work fir you @cryptobrokersou?
