### ISSUE TITLE
[FEATURE] Hide/Unhide unverified assets

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#120]
**Аbstract**

It is really only recommended for user safety that they trade assets which have had some level of due dilligence performed on them first. TurtleNetwork utilizes their IDD services to provide Ticker and Authorizations to assets on the TurtleNetwork: Qualified, Gateway, etc

**Motivation and Purposes**

This is to give users a curated and non cluttered default experience, but they can very easily through a toggle in the settings, under advanced, show all assets.

**Specification**

User has to already have enabled the advanced features through the check box in settings. Then they will see under the set script button a toggle for assets: "Show ALL assets" (switchie)

**Comment by fyrak1s** [comment]
How do the assets get verified?

**Comment by BlackTurtle123** [comment]
> How do the assets get verified?

By sending a ticker request either to TN core team, or another data service provider.
Only the people who allowed this data provider will see this ticker

**Comment by BlackTurtle123** [comment]
Closed for now
