### ISSUE TITLE
[FEATURE] Add ltc gateway, it's deposit type

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#121]
**Аbstract**
Add the ltc gateway, it's migrated to deposit gateway framework 
ltcgw.turtlenetwork.eu

**Comment by xucito** [comment]
What is the gw and the regex?

**Comment by BlackTurtle123** [comment]
ltcgw.turtlenetwork.eu
^[LM3][a-km-zA-HJ-NP-Z1-9]{26,33}$

**Comment by BlackTurtle123** [comment]
added
