### ISSUE TITLE
[BUG] Many Innactive Pairs in UI

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#122]
Problem which needs open discussion.

Current solutions are to hide inactive pairs with a checkbox

One is also having a star column before others with "active" pairs

**Comment by BlackTurtle123** [comment]
TODO:
1) Add checkbox to hide inactive pairs (0 volume past 24 hours)
2) Show all qualified + gateway assets against every base pair.
Currently only 4or 5 assets are showed. This should be a full list from gw on top followed by qualified ones
