### ISSUE TITLE
A "Gateways" page as a main tab next to "Wallet" & "Exchange" selection in the Turtle DEX

### ISSUE THREAD

**Issue by Samurai6** [TurtleNetwork/TurtleNetworkGUI#124]
**Аbstract**
A main page to display all available gateways

**Motivation and Purposes**
Make the DEX a lot simpler direct and user friendly

** Specification**
At the top left where the wallet and exchange tab is, add a third tab page dedicated for Gateways. This will have a clear list and basic instructions of what Gateways are and used for inside the wallet.

**Backwards Compatibility**
Can your proposition affect any existing features?

**Examples and Implementation**
![image](https://user-images.githubusercontent.com/43660434/77952502-c3dfac80-7299-11ea-86e4-2aea1c539bfe.png)

**Comment by BlackTurtle123** [comment]
What would be the adventage above the normal integration? Why would a user needs this page?

**Comment by Samurai6** [comment]
Gateways are a main feature of TN and this could help organize supported gateways outside clicking the deposit button for assets needed to be pinned to main dashboard. If the goal is to be user friendly, features integral to the DEXs usage should be easy to reach, clear and obvious for people with basic understanding to find. If it's a lot of work I understand not really trying to add to the work load just giving suggestion for improvements, I'd do it myself if I had the capabilities.

**Comment by fyrak1s** [comment]
@Samurai6 If you care about it, you could help us by working out an exact list of features, a basic structure, or even a simple mockup, how you would imagine this should look.
So we get a better picture.

It would drastically increase chances of it getting implemented, especially if it creates real value for the user that we might miss.

**Comment by Samurai6** [comment]
Sure np, I can give a better explanation and try to make a mock up of what the exchange deposit page would look like

**Comment by DreamTrims** [comment]
My suggestion would be to use a Deposit button at the top navigation, once logged in, so its: 
Exchange | Wallet | Deposit

When Deposit is clicked then will lead you straight to the Gateway section.

**Comment by BlackTurtle123** [comment]
> My suggestion would be to use a Deposit button at the top navigation, once logged in, so its:
> Exchange | Wallet | Deposit
> 
> When Deposit is clicked then will lead you straight to the Gateway section.

This ticket contains this if I am not mistaken?
If so please endorse it with a like etc
https://github.com/TurtleNetwork/TurtleNetworkGUI/issues/30

**Comment by BlackTurtle123** [comment]
Probably won't be implemented since dev capacity is down.

**Comment by BlackTurtle123** [comment]
TODO:
1) Add the deposit modal linked to the Receive/deposit in the header. Follow this structure
Exchange | Wallet | Deposit

**Comment by dev-campos** [comment]
Should I remove the original receive button?

**Comment by BlackTurtle123** [comment]
@dev-campos, no we just add shorter link to depositing gw assets. But we leave all intact.
Note, only deposit with a link to gw deposits should be added to the top header.

**Comment by dev-campos** [comment]
I just added a deposit button to the header that behaves exactly the same way as the receive button in the wallet, is that correct?

**Comment by BlackTurtle123** [comment]
It should brinf up the gateways page directly. When you click receive you see gateways. This page should be directly added. So 1 level deeper

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/80528411-2eb5fd80-8996-11ea-8038-d976e4d09bbb.png)
this should be shown directly when clicking deposit.
Without the myaddress/gateways menu/header. just the print screen

**Comment by BlackTurtle123** [comment]
Ps i am also always around on TG

**Comment by BlackTurtle123** [comment]
I think it's nicely done @Samurai6 you also satisfied?

**Comment by BlackTurtle123** [comment]
@dev-campos seems that dark theme went broken
![image](https://user-images.githubusercontent.com/16037736/81576470-957ce300-93a8-11ea-930b-b0ba1805058c.png)

**Comment by dev-campos** [comment]
I will fix this rn

**Comment by BlackTurtle123** [comment]
> I will fix this rn

Thanks a lot

**Comment by dev-campos** [comment]
pr is up

**Comment by BlackTurtle123** [comment]
@dev-campos seems fine, thanks for the contribution, good job
