### ISSUE TITLE
[FEATURE] ALL should be first tab on Exchange

### ISSUE THREAD

**Issue by iammortimer** [TurtleNetwork/TurtleNetworkGUI#132]
When opening the Exchange the initially opened and first tab in the Pairs overview (on the left) should be ALL.

**Comment by gord0b** [comment]
It was changed, as TN is more relevant and All takes longer to initially load.

**Comment by BlackTurtle123** [comment]
> When opening the Exchange the initially opened and first tab in the Pairs overview (on the left) should be ALL.

Yes we changed this to show TN pairs more. I agree with this

**Comment by iammortimer** [comment]
Ok, wasn't aware (or just didn't remember) that decission :)
