### ISSUE TITLE
[BUG] Gateway wording and color is unclear

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#133]
**Describe the bug**
Gateway text is unclear and colors aren't very readable.

New Wallet - Gateway text doesnt make sense
"Dont forget to use 3JmWmAA5WkkujP2JpmMWyWYGm5drbBPeoWH as the attachment."
1: All the text is orange and cant really see it
2: The text isnt accurate and cant see it easily, you guys need to read this stuff like a newbie

**Comment by iammortimer** [comment]
Fees need to be shown as well

**Comment by iammortimer** [comment]
And disclaimer link / e-mail should be clickable

**Comment by gord0b** [comment]
3: Text doesnt have a heading, heading should be bold. Possibly highlight the Wallet address in RED, to make it more visible.

**Current Text;**
Dont forget to use
'Address inserted' as the 
attachment.

**Proposed Idea;**
Important: Send with a Description (Use as heading in bold)
Insert: 'Address inserted' (Make address RED)
into the Description field.

**Note:** Waves Platform wallet doesnt use 'attachment', they use 'Description'. So Waves and TN Gateways need to use 'Description' when receing from Waves Platform

![wallet_gw_issue3](https://user-images.githubusercontent.com/34238250/78263506-56828480-7502-11ea-82c6-cb39ed978ee9.png)

**Comment by gord0b** [comment]
4: 'Info box' when clicking on 'i' in the 'Copy and Share Address Section' - has incorrect text.

TN, Waves and Pirate Chain Gateway pages have this issue.
![wallet_gw_issue2](https://user-images.githubusercontent.com/34238250/78263273-03103680-7502-11ea-80db-b8ae2c21696a.png)

**Comment by BlackTurtle123** [comment]
> 4: 'Info box' when clicking on 'i' in the 'Copy and Share Address Section' - has incorrect text.
> 
> TN, Waves and Pirate Chain Gateway pages have this issue.
> ![wallet_gw_issue2](https://user-images.githubusercontent.com/34238250/78263273-03103680-7502-11ea-80db-b8ae2c21696a.png)

This one seems fixed

**Comment by BlackTurtle123** [comment]
TODO:
1) Fees need to be shown
2) disclaimer link / e-mail should be clickable
3) 4 Headings (in orange should be bold)
4) Address should be red to draw more attention
5) Use a more friendly color then orange?

**Comment by fyrak1s** [comment]
>5. Use a more friendly color then orange?

![gwcolorsdark](https://user-images.githubusercontent.com/2538022/80665976-3e6b3a00-8a9b-11ea-9afb-5567e7be9765.png)

What about the orange in dark mode? Doesn't look too bad imo... Shall we keep it or use a different color for both themes?

**Comment by BlackTurtle123** [comment]
> > 1. Use a more friendly color then orange?
> 
> ![gwcolorsdark](https://user-images.githubusercontent.com/2538022/80665976-3e6b3a00-8a9b-11ea-9afb-5567e7be9765.png)
> 
> What about the orange in dark mode? Doesn't look too bad imo... Shall we keep it or use a different color for both themes?

We can keep it, but for white mode we do need another one for sure

**Comment by fyrak1s** [comment]
![image](https://user-images.githubusercontent.com/2538022/80754781-ecc0bf00-8b2f-11ea-8bff-3d074765191b.png)
![image](https://user-images.githubusercontent.com/2538022/80755003-4f19bf80-8b30-11ea-85e9-50ed0ba857a7.png)


Do the colors look alright?

**Comment by BlackTurtle123** [comment]
For me it looks fine. Let me tag some others. @gord0b @iammortimer

**Comment by fyrak1s** [comment]
>Proposed Idea;
Important: Send with a Description (Use as heading in bold)
Insert: 'Address inserted' (Make address RED)
into the Description field.

Updated with @gord0b's suggestions:
![image](https://user-images.githubusercontent.com/2538022/80759625-e20a2800-8b37-11ea-8655-796221db8959.png)
![image](https://user-images.githubusercontent.com/2538022/80759784-272e5a00-8b38-11ea-9193-753d3d83ff0e.png)

**Comment by fyrak1s** [comment]
Yeah so for the bright theme I dont know which other color to use than green. Orange doesn't have enough contrast. And when I try to make it darker it starts to look brownish and ugly.

For the dark theme, both light green and orange is fine as you see.

But you guys should decide:)

**Comment by iammortimer** [comment]
Looks a lot better

**Comment by gord0b** [comment]
The green headings are much better, shows well in light and dark - thx

**Comment by fyrak1s** [comment]
Great one last thing, how do you want the fees to be shown, at which place and what are the exact fees (are they always the same or dependant on gw etc)?
>1. Fees need to be shown

**Comment by BlackTurtle123** [comment]
> Great one last thing, how do you want the fees to be shown, at which place and what are the exact fees (are they always the same or dependant on gw etc)?
> 
> > 1. Fees need to be shown

Sorry for me slow reply. If it happens again hit me up on TG. 
Eumh the fees can be found with the /api/fullinfo api call from each gw. They are different for ezch gw. But the api call is always the same

**Comment by BlackTurtle123** [comment]
@Nuc1eoN it seems something goes wrong with variable parsing.
![image](https://user-images.githubusercontent.com/16037736/81563965-5003ea00-9397-11ea-8c20-ecc48cd4d362.png)
![image](https://user-images.githubusercontent.com/16037736/81564019-627e2380-9397-11ea-8bbb-70f7c9cc1fca.png)

**Comment by BlackTurtle123** [comment]
Nevermind it was caching

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/81575830-c577b680-93a7-11ea-9d29-1af40e0d90a9.png)
@Nuc1eoN  It seems not all gateways have full instructions.

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/81576970-2fdd2680-93a9-11ea-9535-4df66c3aa1b1.png)

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/81577428-b4c84000-93a9-11ea-9fd9-72c678636294.png)
Feedback from @gord0b 
"If you read the wording, maybe the address should be moved-up near the top (under "Send only to this deposit address").. The 1st thing you do is insert your address"

**Comment by BlackTurtle123** [comment]
Waiting for some last small fix by @Nuc1eoN

**Comment by Samurai6** [comment]
![image](https://user-images.githubusercontent.com/43660434/82493878-b0d9a380-9ab6-11ea-862e-a850bffea594.png)
Here the font and color of the link to deposit instructions doesn't stand out from the other text people wont realize they can click on it initially

**Comment by fyrak1s** [comment]
Lemme try out a few versions and you guys can vote for the new color

**Comment by fyrak1s** [comment]
![image](https://user-images.githubusercontent.com/2538022/82554074-8561c200-9b65-11ea-9b6e-0a4e40d36b43.png)
![image](https://user-images.githubusercontent.com/2538022/82554086-8db9fd00-9b65-11ea-82e0-47fc1cb9fc08.png)

How about this? @BlackTurtle123 @Samurai6 @gord0b ?

**Comment by BlackTurtle123** [comment]
Pr seems fine and to be solved for me

**Comment by BlackTurtle123** [comment]
The TN gateway now tells the right answer.
As far for colors, the above is good enough for me

**Comment by BlackTurtle123** [comment]
@Nuc1eoN just go ahead with the colors and then I think we can close the issue fully unless i oversee something

**Comment by fyrak1s** [comment]
@BlackTurtle123 hey sure that's the plan, I am gonna implement it today or tomorrow probably

**Comment by gord0b** [comment]
- Might be a good idea to remove the ‘full stop’ at the end of the gateway url.
- Url clickable to correct gateway, better for security

**Comment by fyrak1s** [comment]
> Url clickable to correct gateway, better for security

@gord0b Which URL is not clickable?

**Comment by gord0b** [comment]
> 
> 
> > Url clickable to correct gateway, better for security
> 
> @gord0b Which URL is not clickable?

Apologies, gateway link is clickable, no change required for that item )
