### ISSUE TITLE
TN price in dollars seems wrong [BUG]

### ISSUE THREAD

**Issue by bassanou** [TurtleNetwork/TurtleNetworkGUI#135]
**Describe the bug**
TN price in dollars seems wrong.

**Expected behavior**
i think the price of TN in dollars should be calculated in function to its price on the most liquid market.

**Screenshots**

![Annotation 2020-04-03 115732](https://user-images.githubusercontent.com/62956112/78348964-2808b600-75a3-11ea-947e-a6045a2a7ab3.png)

**Desktop (please complete the following information):**
 - OS: [win 10]
 - Browser/JVM [chrome]
 - Version [80.0.3987.149 (Build officiel) (64 bits)]

**Additional context**
i love this wallet! good luck!

**Comment by BlackTurtle123** [comment]
It's currently actually using the TN/BTC price will be changed in the future

**Comment by BlackTurtle123** [comment]
I fixed it.
Next release the price will be in USDT
