### ISSUE TITLE
ID ARR token instead of its symbol on ARRR/TN market [BUG]

### ISSUE THREAD

**Issue by bassanou** [TurtleNetwork/TurtleNetworkGUI#136]
**Describe the bug**
ID ARR token instead of its symbol on ARRR/TN market.

**To Reproduce**
1. Go to TN markets
4. See ARRR tolken ID is used instead of its smbol (ARRR)

**Expected behavior**
using the ARRR symbole is much better and user frienfly

**Screenshots**
![Annotation 2020-04-03 120848](https://user-images.githubusercontent.com/62956112/78349824-7bc7cf00-75a4-11ea-9ff6-9d09655b2100.png)

**Desktop:**
 - OS: [win 10]
 - Browser/JVM [chrome]
 - Version [80.0.3987.149 (Build officiel) (64 bits)]

**Additional context**
good luck

**Comment by BlackTurtle123** [comment]
should be fixed with the tickers already
