### ISSUE TITLE
[BUG] Searching under ALL in Exchange doesn't include /TN pairs

### ISSUE THREAD

**Issue by iammortimer** [TurtleNetwork/TurtleNetworkGUI#150]
**Describe the bug**
When searching under ALL in the pairs list on the exchange (some of) the /TN pairs don't show up. 

**To Reproduce**
1. Go to 'Exchange'
2. Select TN in the Pairs overview
3. Search for 'Pool' - you will see Pool Party Node
4. Select All
5. Search for 'Pool' - nothing will show up

**Expected behavior**
Under All i would expect to see all combinations of pairs

**Comment by greywolf42069** [comment]
Issue needs elevation

@xucito 

Need to add this to the TN queue

**Comment by BlackTurtle123** [comment]
I noticed some weird behavior.
When I got a pair on testnet, and I deactivate inactive pairs => it shows this active market like expected
however do i activate inactive pairs => market gone

![image](https://user-images.githubusercontent.com/16037736/82758379-88b7b080-9de6-11ea-9d4b-03a30a5707f2.png)
![image](https://user-images.githubusercontent.com/16037736/82758389-94a37280-9de6-11ea-8712-acfafde515f7.png)

**Comment by BlackTurtle123** [comment]
Update; i found out why this is happening. I will push it tonight.
