### ISSUE TITLE
[Feature] Gateway tokens do not display the projects logo in the wallet.

### ISSUE THREAD

**Issue by Samurai6** [TurtleNetwork/TurtleNetworkGUI#152]
**Аbstract**
 Adding bpsaa & other gateway tokens + verified tokens project logo image next to your holding in your portfolio

**Motivation and Purposes**
To help promote TNDEX listed tokens projects branding and help provide users with some relatable and easily identifiable imagery when browsing threw the DEX

** Specification**
Adding all bpsaa members logo for their respective tokens to help boost dex visual appeal

**Backwards Compatibility**
Can your proposition affect any existing features?

**Examples and Implementation**
Bitcoin, lightcoin, ethereum etc already have logo imagery in your portfolio.

![image](https://user-images.githubusercontent.com/43660434/81235282-8ec92700-8fc8-11ea-98ac-2be2eb444745.png)

**Comment by BlackTurtle123** [comment]
@Samurai6 please if you want to contribute create base64 encoded for this project
https://github.com/TurtleNetwork/oracleManager/blob/master/main.py
https://github.com/TurtleNetwork/oracleManager

**Comment by BlackTurtle123** [comment]
Handled in seperate repo, and almost done, therefor I will close this one
