### ISSUE TITLE
[BUG]Cant's make mass transfer due to error on Fee calculation.

### ISSUE THREAD

**Issue by hugaumr** [TurtleNetwork/TurtleNetworkGUI#157]
While making a mass transfer the windows client doesn't calculate the fee correctly giving an error while sending not allowing to complete transference.

**To Reproduce**
1. Go to mass transfer
2. Select adresses
3. Scroll down to send
4. Click send again
5. The error is there.
![Capturar](https://user-images.githubusercontent.com/56636602/82131000-eb85c800-97a6-11ea-8123-890ee34af9c7.PNG)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
-Win beta Wallet

**Additional context**

**Comment by BlackTurtle123** [comment]
https://github.com/TurtleNetwork/waves-client-config/commit/2494e11f649ba4bf0bb5b1e167387cb6a5131b81

**Comment by BlackTurtle123** [comment]
![image](https://user-images.githubusercontent.com/16037736/82757938-bc450b80-9de3-11ea-90ab-2e0ac7c65c71.png)
Think this bug is resolved
