### ISSUE TITLE
[FEATURE] Lost Bitcoin Deposit.

### ISSUE THREAD

**Issue by upchuq-gnarley** [TurtleNetwork/TurtleNetworkGUI#166]
When depositing Bitcoin into the TurtleNetwork Dex I intended to do so using two separate deposit transactions since the Bitcoin were originating from two different locations. I sent the first Bitcoin deposit tx to the provided gateway address and closed the window. Very soon afterwards (within 5 minutes) I opened the gateway window to perform the second deposit, to which the gateway provided me with the exact same deposit address as it had for the first transaction (I assume because the first tx had not been confirmed) and even though I saw the warning that the address was only "_for one time use only_" I ignored it, since I had become accustomed to the same warning for TN deposits to the TN Dex from Waves but actually using the same address over and over again. If it is not possible to send the second Bitcoin deposit or more deposits until the first/previous deposit has been confirmed then it should be more clear. Perhaps a warning such as "_You must wait until your first deposit is confirmed before making a second deposit or you will lose that money_" or "_Do not send more than one deposit to the same address or you will lose that money_". I believe that this scenario is likely to repeat itself in the future with the current warnings. I also think that this issue should be considered for the Ethereum gateway as well. And to whoever reads this, I failed to make the minimum deposit so I would have not gotten my BTC anyways. So ultimately its my fault! Be sure to read the directions every time!

**Comment by BlackTurtle123** [comment]
Suggested improvements:
Attachment based:
![image](https://user-images.githubusercontent.com/16037736/85928462-7c26ec00-b8ad-11ea-9f4b-05bd90b0799b.png)
Deposit addr based:
![image](https://user-images.githubusercontent.com/16037736/85928488-9791f700-b8ad-11ea-9610-0c5fb5d40b90.png)
Tunnel based:
![image](https://user-images.githubusercontent.com/16037736/85928507-b09aa800-b8ad-11ea-8dc9-fa63af2a91e4.png)

**Comment by upchuq-gnarley** [comment]
Ok, for the TurtleNetwork Gateway text:
1) Send only to this deposit address.
   -Instead I would suggest:
     Send only TN to this deposit address.
2) Sending any other currency to this address may result in the loss of your deposit.
    -Instead I would suggest:
      Sending any other currency other than TN to this address may result in the loss of your deposit.
3) Important: Send with a Description 
     -Instead I would suggest either:
        a)Important: Send as a Description
                     -or-
        b)Important: Your TurtleNetwork address must be included in the description field or you may/will lose that money.
          * As a personal note number 3) is very confusing because it sounds as if it is asking for a description of the deposit such as amount and type of
            asset instead of the location for the TN address.

For the Bitcoin Gateway text:
1) Send only to this deposit address.
     -Instead I would suggest:
        Send only Bitcoin to this deposit address.

2) Important: This address is for one time use only!
     -Instead I would suggest:
         Important: This address is for one time use only and can only accept one deposit!

3) Please wait till your deposit is completed before doing a second one. Ignoring this might result in the loss of your funds.
        -Instead I would suggest:
             You must wait for your initial Bitcoin deposit to be confirmed on the TurtleNetwork blockchain before receiving another  Bitcoin deposit address for the Turtlenetwork. If you make more than one Bitcoin deposit to the same deposit address you will lose those deposits.

For the Ethereum Gateway text:
1) To deposit Ethereum using a tunnel, use https://ethgw.turtlenetwork.eu. Be aware, tunnels are one time use, and can only process one transfer at the same time.
      -Instead I would suggest:
          To deposit Ethereum into the TurtleNetwork you must use a tunnel provided at https://ethgw.turtlenetwork.eu. Warning! Tunnels are one time use only
          and will be permanantly closed after that one use! Sending more than one deposit through the same tunnel will result in the loss of that deposit!

**Comment by upchuq-gnarley** [comment]
The suggestions I have made are very straight forward and specific which makes them lengthy. I have reasons for all the changes that I have suggested but mostly they (my reasons ) are based on the belief that as TN grows, it will attract more users, many with larger deposits, who for whatever reason will make mistakes. I hope the new wording will reduce deposit issues in the future for both depositors, gateway operators and the TurtleNetwork in general.  The suggestions should not be considered perfect but more as a work in progress.

**Comment by gord0b** [comment]
ETH GW support address should be: support@turtlenetwork.eu not info@turtlenetwork.eu

**Comment by NourElYakine2022** [comment]
in the TN gateway page the emphasis sould be on the attachement thing. 
instead of: ''Send only to this deposit address. This address is for 1 time use only!'' i suggest to put : "to deposit TN from waves wallet to your TN wallet, send TN to the TN gateway address: 3PPCNT4wWpyGyHQ5bkKFi9wyCKP8hbeRkTG, with your TN wallet address in attachement. 
adding an image may help to understand well the process

![suggestion](https://user-images.githubusercontent.com/65791190/85944230-6eb54480-b935-11ea-9b58-35f3110a38a3.png)

**Comment by gord0b** [comment]
Edits based on upchuq-gnarley suggestions;

**TN Gateway:**
**#1**
**Original Text:** "Send only to this deposit address."

**Change to:** "Send only TN to this deposit address."

**#2**
**Original text:** "Sending any other currency to this address may result in the loss of your deposit."

**Change to:** "**Note:** Only send TN to this address, otherwise may result in the loss of deposit." -- then highlight text in orange (same as deposit fee colour)

**#3**
**Original text:** "Important: Send with a Description
Insert: 'ReplaceAddress' into the Description field"

**Change to:** "**Required:** Send TN with deposit address in Description
Insert 'ReplaceAddress' into the Description field.
**Note:** Deposit address must be included in the description field, otherwise may result in the loss of deposit." --- then highlight text from 'Note' in orange (same as deposit fee colour)

**Comment by BlackTurtle123** [comment]
BTC,LTC,.. gateways:
![image](https://user-images.githubusercontent.com/16037736/85944269-cb186400-b935-11ea-8736-1395809d840d.png)
ETH, EHTO,.. gateways:
![image](https://user-images.githubusercontent.com/16037736/85944325-2fd3be80-b936-11ea-886a-bac497ccecbe.png)

**Comment by NourElYakine2022** [comment]
anyway, the attachement thing should be highlighted and put on the top of the page since many traders are used to send to a unique address. in our case the traders will send to a gateway address with an attachement that indicates the destination of deposioted TN.

**Comment by BlackTurtle123** [comment]
WAVES/TN/..
![image](https://user-images.githubusercontent.com/16037736/85945317-4cbfc000-b93d-11ea-8b6c-f4d4f7b48887.png)

**Comment by BlackTurtle123** [comment]
With the updated implemented this issue can be closed for now
