### ISSUE TITLE
[BUG] Complete Wallet Address not visible (In top right main menu above Aliases option)  

### ISSUE THREAD

**Issue by Tradecoin-Token** [TurtleNetwork/TurtleNetworkGUI#171]
**Describe the bug**
Near Copying the address from main dropdown menu of top right corner, the address window need to be fixed and adjusted according to address length, during visual display of address for copying it is **escaping last 3 characters of address** which are not completely visible and currently showing in 3 dots.

**To Reproduce**
Steps to see the behavior:
1. Go to 'Top right corner' drop down menu
2. Wallet Address Copying just Above the "Aliases" menu

**Expected behavior**
Address must be completely visible during copying to ensure for right address selection and avoid misunderstanding for multiple wallet address of same initials.

**Screenshots**
![image](https://user-images.githubusercontent.com/8797899/97155711-c48ee180-179b-11eb-9475-fb5707ef8f03.png)

**Desktop (please complete the following information):**
Desktop Wallet

**Comment by manoj815** [comment]
https://github.com/TurtleNetwork/TurtleNetworkGUI/blob/dev/src/modules/ui/directives/mainHeader/less/largeHeader/largeHeader.less 
on line no 106 change padding: 25px; to padding: 20px

**Comment by voiletrays** [comment]
https://github.com/TurtleNetwork/TurtleNetworkGUI/blob/dev/src/modules/ui/directives/mainHeader/less/largeHeader/largeHeader.less
on line no 106 change padding: 25px; to padding: 20px

**Comment by greywolf42069** [comment]
After having tested a variety of long stringed addresses (see below)

<img width="307" alt="image" src="https://user-images.githubusercontent.com/55455281/99158060-52236a00-2694-11eb-9ab8-66050b36c7a6.png">

the element is not needing to be dynamically adjusted and nothing is broken, all text is now visible and clickable

**Comment by BlackTurtle123** [comment]
WIll push to mainnet
