### ISSUE TITLE
[BUG][FEATURE] Solve contents of Oracle --- Let oracles work, they provide tickers

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#18]
**Аbstract**
We were unable to populate any automatic files, now we must search through waves explorer wallets or attempt to populate ourselves.

**Motivation and Purposes**
We need this to provide data

**Comment by BlackTurtle123** [comment]
Oracles don't work yet, or they don't provide tickers yet.
Figure out how they work. or what we do wrong
