### ISSUE TITLE
[FEATURE] show NFT in wallet

### ISSUE THREAD

**Issue by Tradecoin-Token** [TurtleNetwork/TurtleNetworkGUI#182]
**Аbstract**
Created NFT Assets on TN blockchain are not shown on TN DEX.

**Motivation and Purposes**
Right now TN DEX only message that particular account hold a NFT but people can't do transfer of NFT easily as they can't see NFT Token under their portfolio. They need a special json skill. To minimize such effort a feature must be added to DEX to show NFT in portfolio.

**Specification**
 Created or received NFT asset must relfect in receiver or holder account.

**Backwards Compatibility**
NA

**Examples and Implementation**
Need a similar implementation such as Waves DEX  (waves.exchange) have under "Wallet" menu and "Portfolio" submenu.

**Comment by BlackTurtle123** [comment]
https://nft.turtlenetwork.eu/#/portfolio/3JsWespSeL8gvsU96rhqbDXo6u8LXrWXexs will replace this. An offside NFT wallet.

**Comment by Tradecoin-Token** [comment]
> https://nft.turtlenetwork.eu/#/portfolio/3JsWespSeL8gvsU96rhqbDXo6u8LXrWXexs will replace this. An offside NFT wallet.

Good to see the new step towards NFT via TNShell. 

Good Luck!
