### ISSUE TITLE
[BUG] Inactive Filter Hiding Active Pairs

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#185]
**Describe the bug**
When using the exchange, pairs with volume do not show.

**To Reproduce**
1. Go to Exchange
2. Click on ALL
3. Type into search: XMR
4. Listings populate

**Expected behavior**
Users should see the XMR pairings with volume after step 2. Users should not have to search for active pairs.

**Desktop (please complete the following information):**
 - OS: [ALL]
 - Browser/JVM [ALL]
 - Version [ALL]

**Comment by BlackTurtle123** [comment]
The pair is inactive listed since we can't calculate the volume since it's a 0 TN volume pair.
So no bug, feature as intended it seems
