### ISSUE TITLE
[BUG] After auto logout, you can't log in again

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#19]
**Describe the bug**
fix bug after auto logout, you can't log in again

**To Reproduce**
login to client
let it automatically log you out from inactivity

**Expected behavior**
unable to login

**Screenshots**
nAn

**Desktop (please complete the following information):**
mr turtle pc

**Comment by xucito** [comment]
Allow for forced redirection to wallet after re-signin
