### ISSUE TITLE
[FEATURE] Make 2 labels in the client for gateways

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#25]
Currently there is one client label:
gateway
create another label for 3rd-party gateways.

what is a 3rd party gw? a gw not run officially by TN team.
Why we need this? To inform the users about the gateways => transpirancy.

When sending coins through a 3rd party gateway, give an additional pop up.

Best to make this list configurable in the config ( easy to reuse for cryptobrokers and so they can mark gateways as third party etc etc)

**Comment by greywolf42069** [comment]
This will be used in Polarity for the Staking system
