### ISSUE TITLE
[BUG] cant create an Alias

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#26]
In Wallet, top right in Account then Aliases.
When trying to create a new alias the below error is shown;

Error;
{"error":112,"message":"State check failed. Reason: . Fee for CreateAliasTransaction (2000000 in TN) does not exceed minimal value of 1000000000 TN.","tx":{"senderPublicKey":"AmRgG3zG1EywwcSce3uizSYdw31dZFCeK7Wa7qHgCZ34","sender":"3XWgxAo2jvydtuMp3Z8LfGxQmo2SNreB7vb","feeAssetId":null,"proofs":["2AmzosRzNziZLEKiuqVQoCf3cXbaJ5dvfqzTKCnKaUx9jjuUrTWQDULvSA7vdq

**Comment by BlackTurtle123** [comment]
This should be tackled by adding a new fee value to this file:
https://github.com/TurtleNetwork/waves-client-config/blob/master/fee.json
ID 11 is a alias transaction. (https://docs.wavesplatform.com/en/ride/structures/transaction-structures/#tokenisation)

And then the wallet should use the fee from this file, instead default fee

**Comment by xucito** [comment]
ID for createAlias transaction is 10. Fix to [fee.json](https://github.com/TurtleNetwork/waves-client-config/blob/master/fee.json) is complete

**Comment by gord0b** [comment]
Confirmed fixed - thank you
