### ISSUE TITLE
[BUG] - Exchange default pair duplicate

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#29]
'Waves' pair is listed twice as a pair on the Exchange default view / remove.
Move 'All' to the dropdown section

Suggested default menu below;
TN-BTC-WAVES-ETH (Dropdown with LTC, ALL)

**Comment by greywolf42069** [comment]
![image](https://user-images.githubusercontent.com/55455281/75270860-e07f5500-57c0-11ea-9820-dbd1e5a21770.png)
