### ISSUE TITLE
[FEATURE] - Wallet Dashboard Improvements

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#30]
**Wallet Dashboard Receive section is not 100% accurate**

**Wallet / Dashboard / Receive section**
**1:** Inverse tabs making 'Invoice' the default selection.
**2:** Rename both tabs;
**2a**: 'CryptoCurrency' Tab rename to 'Gateways' &
**2b:** 'Invoice' Tab rename to 'My Address'

**Wallet Dashboard - new section for easy access to Scan a QR code**
3: Add new 'Scan' section next to 'Send', 'Receive' 'Add-Scan-Tab' heading tabs in Wallet / Dashboard;
Note: Scan uses Integrated camera option currently found in Wallet / Dashboard then 'Send, Recipient, click scan icon' but not easy to access, easier access to 'QR scanning' is required.

**[Send, Receive, Scan] shortcuts on the main header**
4: Add [Send, Receive, Scan] shortcuts on the main header - 'left of the profile section' on the right.
Three shortcuts will be used for much quicker access (less clicks) to sections of the current wallet, especially during mobile access.
shortcut1: 'Send' link shortcut to Wallet / Dashboard /Send
shortcut2: 'Receive' link shortcut to Wallet / Dashboard / Receive
shortcut3:  'Scan' link shortcut to Wallet / Dashboard / Scan (New section, as per above)

**Comment by BlackTurtle123** [comment]
2a
and 
2b 
should be a first version in the next testnet release

**Comment by BlackTurtle123** [comment]
1A done

**Comment by BlackTurtle123** [comment]
> **Wallet Dashboard - new section for easy access to Scan a QR code**
> 3: Add new 'Scan' section next to 'Send', 'Receive' 'Add-Scan-Tab' heading tabs in Wallet / Dashboard;
> Note: Scan uses Integrated camera option currently found in Wallet / Dashboard then 'Send, Recipient, click scan icon' but not easy to access, easier access to 'QR scanning' is required.
> 
> **[Send, Receive, Scan] shortcuts on the main header**
> 4: Add [Send, Receive, Scan] shortcuts on the main header - 'left of the profile section' on the right.
> Three shortcuts will be used for much quicker access (less clicks) to sections of the current wallet, especially during mobile access.
> shortcut1: 'Send' link shortcut to Wallet / Dashboard /Send
> shortcut2: 'Receive' link shortcut to Wallet / Dashboard / Receive
> shortcut3: 'Scan' link shortcut to Wallet / Dashboard / Scan (New section, as per above)

above is still open

**Comment by BlackTurtle123** [comment]
discussed this with gordon, we can close it for now
