### ISSUE TITLE
[BUG] - Url of DEX pairs contains 'dex-demo'

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#35]
The URL of DEX pairs contains "dex-demo", this isnt clean as "demo" shouldn't be mentioned in the URL, change to "dex"

**Example;**
https://testnet.wallet.turtlenetwork.eu/dex-demo?assetId2=TN&assetId1=4bXds5VEHFQth6AhpF1k6rjvNKzaMf1Yz2Wab9pn9msD

**Example;**
https://testnet.wallet.turtlenetwork.eu/dex-demo?assetId1&assetId2

**Other to change**;
Main Page on https://testnet.wallet.turtlenetwork.eu/ has a link "To view more traded pairs click
View Exchange" that clicks through to "https://testnet.wallet.turtlenetwork.eu/dex-demo"

**Comment by xucito** [comment]
This is expected behavior if you are not signed in. Once you sign in and browse to dex, it will be pathed /dex
