### ISSUE TITLE
[BUG] By hoovering the button it still displays a blue one

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#39]
![image](https://user-images.githubusercontent.com/16037736/75624215-acd26f80-5bb2-11ea-8c42-28b9fab4528c.png)

**Comment by xucito** [comment]
Updating color scheming with following conversions.
1751ec => 51ec17
2051d3 => 51d320
1a4ac8 => 4ac81a
0d3dba => 3dba0d
