### ISSUE TITLE
[BUG] Download buttons still download waves clients.

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#41]
![image](https://user-images.githubusercontent.com/16037736/75624409-2028b100-5bb4-11ea-9c09-9e8aa7b917a6.png)

**Comment by greywolf42069** [comment]
![image](https://user-images.githubusercontent.com/55455281/75636634-fb4d3180-5be5-11ea-86cf-cd00616d80b4.png)

Line 45 of LargeHeader.html
