### ISSUE TITLE
[BUG] Token issue rules still contain waves

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#43]
**Describe the bug**
When issueing a token, and looking at the rules, they still contain waves.

![image](https://user-images.githubusercontent.com/16037736/75624656-9af2cb80-5bb6-11ea-847b-f9ed0ba677b6.png)

**Comment by greywolf42069** [comment]
it is defaulting to locale-backup, this is changed in the english locale on git just delete locale-backup

**Comment by greywolf42069** [comment]
![image](https://user-images.githubusercontent.com/55455281/75636430-4d8d5300-5be4-11ea-8eb6-1d1564e0aa52.png)

**Comment by greywolf42069** [comment]
sent corrected locale and locale-backup to @BlackTurtle123

**Comment by xucito** [comment]
Changed all instances of WAVES DEX with Turtle Network DEX
