### ISSUE TITLE
[BUG] DELETE ROADMAP IN FULL

### ISSUE THREAD

**Issue by BlackTurtle123** [TurtleNetwork/TurtleNetworkGUI#44]
**Describe the bug**
Currently it shows ugly template vars, delete it in full

**To Reproduce**
Go to wallet home page

**Screenshots**
![image](https://user-images.githubusercontent.com/16037736/75628039-a1447000-5bd5-11ea-807b-2c38a9bb92ac.png)

**Comment by greywolf42069** [comment]
modification made to Roadmap.js

made it only 2 items

tried to replace text lets see what happens.

**Comment by BlackTurtle123** [comment]
Update, delete this fullt @xucito
