### ISSUE TITLE
[BUG] Landing Carousel not lined up to mainnet asset prices

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#45]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/55455281/75633721-09428880-5bcd-11ea-9269-92ac89f551da.png">

It see TN / Waves but not other pairs

**Comment by xucito** [comment]
The data from these feeds comes from 24hrs and the above should be testnet prices. From the screenshot the price is loading.
