### ISSUE TITLE
[BUG] - Token Creation Node link incorrect

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#59]
**Describe the bug**
Token Creation Node URL incorrect on the token generation page

**To Reproduce**
In the Main menu Item 'Create Token' at the bottom of the token generation page, update URL from https://privatenode2.blackturtle.eu to https://tnnode2.turtlenetwork.eu

**Screenshots**
![Issue7](https://user-images.githubusercontent.com/34238250/76144021-cd07a000-6084-11ea-85cf-7de3b371d6cb.png)

**Comment by greywolf42069** [comment]
locale fix added merging now

**Comment by BlackTurtle123** [comment]
solved, verified
