### ISSUE TITLE
[FEATURE] TrueUSD Gateway and Pinned Item

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#7]
Add gateway address for TrueUSD for the USDT gateway, rename and change description, asset id, and set picture to TrueUSD

**Comment by BlackTurtle123** [comment]
Integrate TUSD gateway=> https://www.rcanelabs.com/gateways
Dont reuse wrong assets but rather use a new clean asset.
