### ISSUE TITLE
[FEATURE] Gateway Deposit, Generate QR Code

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#75]
**Аbstract**
This is to make the process of deposit through gateway easier for end users.

**Motivation and Purposes**
When you go to deposit, the QR code should grab the information needed to auto fill when scanned by an outside network client. attachment is filled and only amount is open actually. It should not allow you to add an attachment to transaction to the gateway.

**Comment by iammortimer** [comment]
https://docs.waves.exchange/en/waves-exchange/waves-exchange-client-api/waves-exchange-client-payment-api#process gives a nice description of the process. 
Quick search of the forked codebase doesn't give any results, could be this is new in waves.exchange
