### ISSUE TITLE
[BUG] Pinning Assets list loads nothing

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#80]
This function did work previously before this lastest merge.

Open dashboard, click on the plus next to TurtleNetwork base asset. 

Should populate a list automatically.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/55455281/76692297-7836cd00-6622-11ea-9650-037d590b513f.png">

**Comment by BlackTurtle123** [comment]
Probably in connection with #77 since it loads the same asset list
