### ISSUE TITLE
[BUG] Dark Mode Tradingview Banner doesnt Change

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#85]
Enable dark mode, go to dex, check dis

<img width="840" alt="image" src="https://user-images.githubusercontent.com/55455281/76705400-c93fd300-66ad-11ea-8b59-799ad43ea847.png">

**Comment by xucito** [comment]
Potentially a bug with TradingView, there is no override occurring for this.
