### ISSUE TITLE
[BUG] Download links non functioning

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#88]
<img width="157" alt="image" src="https://user-images.githubusercontent.com/55455281/76707157-ee870e00-66ba-11ea-9dfc-81983104b752.png">
From the splash clicking the links takes you to a directory that does not  have read permissions, I cannot download or curl,

**Comment by BlackTurtle123** [comment]
@gord0b tested the windows version, but it seems to build something totally not TN related (screenshot)
![image](https://user-images.githubusercontent.com/16037736/76742996-3ae15500-6772-11ea-8197-77e52903f153.png)

**Comment by BlackTurtle123** [comment]
I will have a look at it if I got time popping up
