### ISSUE TITLE
[BUG] trading view changing candle types does nothing

### ISSUE THREAD

**Issue by iammortimer** [TurtleNetwork/TurtleNetworkGUI#89]
**Describe the bug**
In Exchange, changing the candle type to anything other than 'Candles' does nothing.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Browser/JVM: Brave
 - Version: 1.4.96

**Comment by xucito** [comment]
This issue only affects swapping between normal candles and Heikin Ashi and vice versa

**Comment by iammortimer** [comment]
For me it occured with any type of candle
