### ISSUE TITLE
[BUG] - footer update - text and links

### ISSUE THREAD

**Issue by gord0b** [TurtleNetwork/TurtleNetworkGUI#92]
**Describe the bug**
Various items in the footer of https://testnet.wallet.turtlenetwork.eu (main wallet page) need to be updated;

**To Reproduce**
1. Image above 'Brought to you by CryptoBrokers and Turtle Network (based on WavesPlatform)' text in footer, URL goes to https://wavesplatform.com which is incorrect. Image is also cutoff. Don't see the value of an image of the logo in the footer, remove.

2. "© 2019 Waves Platform" should be changed to "© 2020 Turtle Network"

3. "support@turtlenetwork.eu" URL clicks to "https://support.wavesplatform.com" which is incorrect and should click to "support@turtlenetwork.eu"

4. Under 'Products & tools' section in footer, remove current text and links and add the following;
4a: 'Website' with URL link to https://www.turtlenetwork.eu
4b. 'Turtle Network Statistics' with URL link to http://statistics.turtlenetwork.eu
4c. 'Turtle Network Explorer' with URL link to https://explorer.turtlenetwork.eu
4d. 'TurtleShell' with URL link to https://chrome.google.com/webstore/detail/turtleshell/billhkeiifjfbbkmmfpcpchikbajnfje
4e. 'Turtle Network Mobile Wallet' with URL link to https://play.google.com/store/apps/details?id=com.tn.wallet
4f. 'Old Turtle Network Wallet' with URL link to https://client.turtlenetwork.eu

5. Under 'For developers' section in footer add the following;
5a. 'API' with URL link to https://api.marketdata.turtlenetwork.eu
5b. Remove 'API' from the Menu Header.

6. Under the 'Social' section in footer add the following;
6a. 'Facebook' with a URL link to https://www.facebook.com/TurtleNetworkTN
6b. 'Instagram' with a URL link to https://www.instagram.com/turtlenetworktn
6c. 'Reddit' with a URL link to https://www.reddit.com/r/TurtleNetwork
6d. 'Bitcointalk' with a URL to https://bitcointalk.org/index.php?topic=5138663
6e. 'LinkedIN' with a URL to https://www.linkedin.com/company/blackturtle-bvba

**Screenshots**
![newwallet_fix1](https://user-images.githubusercontent.com/34238250/76741770-c65de480-6778-11ea-838c-65dacf0c63ad.png)

**Comment by greywolf42069** [comment]
I have completed points 1, 2, 3 for you @gord0b 

I am merging and making a PR, the rest is for someone with HTML CSS experience

**Comment by BlackTurtle123** [comment]
Still open:
1. Image above 'Brought to you by CryptoBrokers and Turtle Network (based on WavesPlatform)' text in footer, URL goes to https://wavesplatform.com which is incorrect. Image is also cutoff. Don't see the value of an image of the logo in the footer, remove.

2. "© 2019 Waves Platform" should be changed to "© 2020 Turtle Network"

3. "support@turtlenetwork.eu" URL clicks to "https://support.wavesplatform.com" which is incorrect and should click to "support@turtlenetwork.eu"

**Comment by BlackTurtle123** [comment]
> Still open:
> 
> 1. Image above 'Brought to you by CryptoBrokers and Turtle Network (based on WavesPlatform)' text in footer, URL goes to https://wavesplatform.com which is incorrect. Image is also cutoff. Don't see the value of an image of the logo in the footer, remove.
> 2. "© 2019 Waves Platform" should be changed to "© 2020 Turtle Network"
> 3. "[support@turtlenetwork.eu](mailto:support@turtlenetwork.eu)" URL clicks to "https://support.wavesplatform.com" which is incorrect and should click to "[support@turtlenetwork.eu](mailto:support@turtlenetwork.eu)"

I see this was CB his commit

**Comment by gord0b** [comment]
Old link "welcome.TurtleShell" left there - so we have duplicates - please remove

**Comment by gord0b** [comment]
Current 'Turtle Network Explorer' link excludes https - change to https://explorer.turtlenetwork.eu

**Comment by gord0b** [comment]
Under the 'Social' section in footer 'Twitter' link is now wrong, it should be https://twitter.com/TurtleNetworkTN

**Comment by gord0b** [comment]
Under 'Products & tools' section in footer, website not added
4a: 'Website' with URL link to https://www.turtlenetwork.eu

**Comment by fyrak1s** [comment]
> Under the 'Social' section in footer 'Twitter' link is now wrong, it should be https://twitter.com/TurtleNetworkTN

> Under 'Products & tools' section in footer, website not added
> 4a: 'Website' with URL link to https://www.turtlenetwork.eu

Yeah mess-ups on my side. I'm gonna create a hotfix.

> Old link "welcome.TurtleShell" left there - so we have duplicates - please remove

Can't seem to find them. Could you elaborate which ones are dupes? Thank you.

> Current 'Turtle Network Explorer' link excludes https - change to https://explorer.turtlenetwork.eu

Sure I will do that. 'Turtle Network Statistics' has no https version right?

**Comment by BlackTurtle123** [comment]
I fixed the duplicate. The stats site doesn't have https indeed.

**Comment by fyrak1s** [comment]
I think this can be closed?
